services:
  postgres:
    image: postgres:16-alpine
    container_name: ams-postgres
    environment:
      POSTGRES_DB: assignment_management_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - ams_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d assignment_management_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  ams_pgdata:
